INSERT INTO productos (nombre, descripcion, precio) VALUES 
('Refresco Burbuja Cola', 'Refresco sabor cola de 355ml', 12.50),
('Refresco Brisa Tropical', 'Refresco sabor tropical de 355ml', 12.00),
('Refresco Citrus Splash', 'Refresco sabor cítrico de 355ml', 11.50),
('Refresco Naranja Viva', 'Refresco sabor naranja de 355ml', 11.00),
('Refresco Fresa Fusión', 'Refresco sabor fresa de 355ml', 11.00),
('Refresco Lima Twist', 'Refresco sabor lima-limón de 355ml', 11.50),
('Refresco Energía Verde', 'Refresco sabor cítrico energizante de 355ml', 12.00),
('Refresco Cola Fuerte', 'Refresco sabor cola intenso de 355ml', 13.00),
('Refresco Sabor Tamarindo', 'Refresco sabor tamarindo de 355ml', 10.50),
('Refresco Mandarina Dulce', 'Refresco sabor mandarina de 355ml', 10.50),
('Refresco Manzana Espuma', 'Refresco sabor manzana de 355ml', 11.50),
('Refresco Sidra Fresca', 'Refresco sabor manzana fermentada de 355ml', 11.50),
('Refresco Toronja Light', 'Refresco sabor toronja de 355ml', 11.00),
('Refresco Cola Ligera', 'Refresco sabor cola sin azúcar de 355ml', 12.50),
('Refresco Tropical Light', 'Refresco sabor tropical sin azúcar de 355ml', 12.00),
('Refresco Cola Zero Plus', 'Refresco sabor cola sin calorías de 355ml', 12.50),
('Refresco Citrus Zero', 'Refresco sabor cítrico sin calorías de 355ml', 12.00),
('Refresco Espuma Rosada', 'Refresco sabor frutos rojos de 355ml', 11.00),
('Refresco Piña Brillante', 'Refresco sabor piña de 355ml', 10.50),
('Refresco Guayaba Dulce', 'Refresco sabor guayaba de 355ml', 10.50);
